name: plaid_dart
description: A Plaid client package for dart
version: 0.0.1
homepage: https://github.com/deriegle/plaid-dart
author: devinriegle <riegledevin@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  meta: ^1.1.7
  http: ^0.12.0+2

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  mockito: any
